version: "3.8"

services:
  react-app:
    build: .
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # giúp hot reload trên Docker
    command: npm start
